# Generated by Django 2.2.10 on 2020-02-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0093_auto_20200205_0157'),
        ('virtualization', '0013_deterministic_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='cluster_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_machines', to='dcim.Device'),
        ),
    ]
