# Generated by Django 2.2.10 on 2020-02-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0092_fix_rack_outer_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='disk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='memory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
